name: lingua_go
description: "A new Flutter project."
version: 1.0.0+1

# ← tambahkan ini
environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.3
  path: ^1.9.0

  # State Management
  provider: ^6.1.2

  # Enkripsi
  crypto: ^3.0.3

  # Biometric
  local_auth: ^2.3.0

  # Environment
  flutter_dotenv: ^5.2.1

  # Session / Shared Preferences
  shared_preferences: ^2.3.2

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/