name: lingua_go
description: "A new Flutter project."
version: 1.0.0+1

# ← tambahkan ini
environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.3
  path: ^1.9.0

  # State Management
  provider: ^6.1.2

  # Enkripsi
  crypto: ^3.0.3

  # Biometric
  local_auth: ^2.3.0

  # Environment
  flutter_dotenv: ^5.2.1

  # Session / Shared Preferences
  shared_preferences: ^2.3.2

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  image_picker: ^1.1.2

  http: ^1.2.1
  sensors_plus: ^7.0.0 

  # Format waktu
  intl: ^0.19.0
  geolocator: ^11.0.0      # Mengambil koordinat GPS
  timezone: ^0.9.4         # Database zona waktu IANA
  lat_lng_to_timezone: ^0.2.0 # Konversi koordinat ke ID Zona Waktu


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/